Remove pbench functionality
- Remove all --pbench* command line options from README
- Remove pbench execution branch from coremark_pro_run script
- Remove pbench installation note from documentation
- Simplify execution flow to use direct test execution only

diff --git a/coremark_pro/coremark_pro_run b/coremark_pro/coremark_pro_run
--- a/coremark_pro/coremark_pro_run
+++ b/coremark_pro/coremark_pro_run
@@ -256,91 +256,79 @@ run_coremark_pro()
 	fi
 	pushd coremark-pro > /dev/null
 
-	if [ $to_pbench -eq 0 ]; then
-		if [ $to_use_pcp -eq 1 ]; then
-			source $TOOLS_BIN/pcp/pcp_commands.inc
-			setup_pcp
-			pcp_cfg=$TOOLS_BIN/pcp/default.cfg
-			pcp_dir=/tmp/pcp_coremark-pro_$(date +%Y.%m.%d-%H.%M.%S)
-			start_pcp $pcp_dir coremark-pro $pcp_cfg
-			start_pcp_subset
+	if [ $to_use_pcp -eq 1 ]; then
+		source $TOOLS_BIN/pcp/pcp_commands.inc
+		setup_pcp
+		pcp_cfg=$TOOLS_BIN/pcp/default.cfg
+		pcp_dir=/tmp/pcp_coremark-pro_$(date +%Y.%m.%d-%H.%M.%S)
+		start_pcp $pcp_dir coremark-pro $pcp_cfg
+		start_pcp_subset
 
-			pmlogger -c $pcp_cfg -l $pcp_dir/pmlogger.log $pcp_dir/archive & PMLOGGER_PID=$!
-		fi
-
-		#
-		# Iteration of test.
-		#
-		if [ $no_overrides -eq 0 ]; then
-			update_build_options
-		fi
-		#
-		# Silence warnings etc.
-		#
-		make TARGET=linux64 build >>/dev/null 2>&1
-		if [ $? -ne 0 ]; then
-			#
-			# Make failed, rerun and do not keep quiet about it.
-			#
-			make TARGET=linux64 build
-			exit_out "make of test failed, exiting" 1
-		fi
-		numb_cpus=`cat /proc/cpuinfo | grep processor | wc -l`
-		for iter in $(seq 1 1 $to_times_to_run); do
-			
-			#If we're using PCP, snap a chalk line at the start of the iteration and log the run number
-			if [[ $to_use_pcp -eq 1 ]]; then
-	        	start_pcp_subset
-				result2pcp iteration ${run_number}
-			fi
-
-			
-			make_flags="TARGET=linux64 XCMD=-c${numb_cpus} certify-all"
-			make -s $make_flags > coremark_pro_run_${iter}
-			if [ $? -ne 0 ]; then
-				exit_out "Run failed, make $make_flags" 1
-			fi
-
-			# If we're using PCP, snap the chalk line at the end of the iteration
-			if [[ $to_use_pcp -eq 1 ]]; then
-		       	stop_pcp_subset
-			fi
-		done
-
-		# If we're using PCP, stop logging
-	    if [[ $to_use_pcp -eq 1 ]]; then
-	        echo "Stop PCP"
-	      	stop_pcp
-	    fi
-
-		for iter in $(seq 1 1 $to_times_to_run); do
-			produce_summary_report $iter
-		done
-
-		generate_csv_file
-		save_results
-		
-
-		if [ $to_use_pcp -eq 1 ]; then
-			kill $PMLOGGER_PID 2>/dev/null
-	 		wait $PMLOGGER_PID 2>/dev/null
-			
-			stop_pcp_subset
-		fi
-
-		${curdir}/test_tools/save_results --curdir $curdir --home_root $to_home_root --other_files "$summary_file,coremark_pro_run*,test_results_report,$pcp_dir" --results results.csv --test_name coremark_pro --tuned_setting $to_tuned_setting --version $coremark_pro_version --user $to_user
-		popd > /dev/null
-	else
-		popd > /dev/null
-		source ~/.bashrc
-		cd $curdir
-		arguments="${arguments} --test_iterations ${to_times_to_run}"
-		echo $TOOLS_BIN/execute_via_pbench --cmd_executing "$0" $arguments --test ${test_name_run} --spacing 11 --pbench_stats $to_pstats
-		$TOOLS_BIN/execute_via_pbench --cmd_executing "$0" $arguments --test ${test_name_run} --spacing 11 --pbench_stats $to_pstats
-		if [ $? -ne 0 ]; then
-			exit_out "Execution via pbench failed\n" 1
-		fi
+		pmlogger -c $pcp_cfg -l $pcp_dir/pmlogger.log $pcp_dir/archive & PMLOGGER_PID=$!
 	fi
+
+	#
+	# Iteration of test.
+	#
+	if [ $no_overrides -eq 0 ]; then
+		update_build_options
+	fi
+	#
+	# Silence warnings etc.
+	#
+	make TARGET=linux64 build >>/dev/null 2>&1
+	if [ $? -ne 0 ]; then
+		#
+		# Make failed, rerun and do not keep quiet about it.
+		#
+		make TARGET=linux64 build
+		exit_out "make of test failed, exiting" 1
+	fi
+	numb_cpus=`cat /proc/cpuinfo | grep processor | wc -l`
+	for iter in $(seq 1 1 $to_times_to_run); do
+		
+		#If we're using PCP, snap a chalk line at the start of the iteration and log the run number
+		if [[ $to_use_pcp -eq 1 ]]; then
+        	start_pcp_subset
+			result2pcp iteration ${run_number}
+		fi
+
+		
+		make_flags="TARGET=linux64 XCMD=-c${numb_cpus} certify-all"
+		make -s $make_flags > coremark_pro_run_${iter}
+		if [ $? -ne 0 ]; then
+			exit_out "Run failed, make $make_flags" 1
+		fi
+
+		# If we're using PCP, snap the chalk line at the end of the iteration
+		if [[ $to_use_pcp -eq 1 ]]; then
+	       	stop_pcp_subset
+		fi
+	done
+
+	# If we're using PCP, stop logging
+    if [[ $to_use_pcp -eq 1 ]]; then
+        echo "Stop PCP"
+      	stop_pcp
+    fi
+
+	for iter in $(seq 1 1 $to_times_to_run); do
+		produce_summary_report $iter
+	done
+
+	generate_csv_file
+	save_results
+	
+
+	if [ $to_use_pcp -eq 1 ]; then
+		kill $PMLOGGER_PID 2>/dev/null
+ 		wait $PMLOGGER_PID 2>/dev/null
+		
+		stop_pcp_subset
+	fi
+
+	${curdir}/test_tools/save_results --curdir $curdir --home_root $to_home_root --other_files "$summary_file,coremark_pro_run*,test_results_report,$pcp_dir" --results results.csv --test_name coremark_pro --tuned_setting $to_tuned_setting --version $coremark_pro_version --user $to_user
+	popd > /dev/null
 
 }
 
